### ISSUE TITLE
Base path not read/used

### ISSUE THREAD

**Issue by ZA-OI-DE** [StJudeWasHere/seonaut#28]
In many sites, a base path is specified, and all following CSS and definitions are reading that path and then constructing the correct path. 

When scanning a site we noticed that the system does not seem to respect the base path and subsequently generates 100's of 404 errors where it is trying to find URL's

<html lang="en"><head><base href="https://www.domain.com/content/" />

For example, all the linked CSS and JS files in the scanner try to link from the current location of the scanner, and not including and linking from the defined base path. 

For example. 

<link rel="stylesheet" href="[../css/base_styles.css?v=1.6.1](https://www.domainname.com/css/base_styles.css?v=1.6.1)">

<script type="text/javascript" src="[../js/jquery/jquery-3.6.0.min.js?cache=1.6.1](https://www.domainname.com/js/jquery/jquery-3.6.0.min.js?cache=1.6.1)"></script>

<script type="text/javascript" src="[../js/jquery.smartmenus.min.js?cache=1.6.1](https://www.domainname.com/js/jquery.smartmenus.min.js?cache=1.6.1)"></script>

The scanner tries and load and reports 404 on these, for example:

[https://www.domainname.com/subdir/subdir/css/base_styles.css](http://localhost:9000/resources?pid=3&rid=6480&eid=ERROR_40x)

The correct URL should be 
[https://www.domainname.com/css/base_styles.css]

**Comment by StJudeWasHere** [comment]
This should be fixed in 210d4dcea750241dbe5795d4eb40f8af2624c5a5. 

Thanks for reporting.

**Comment by ZA-OI-DE** [comment]
Thank you, the loop is no longer happening, but it is still not applying the base path correctly. 

For example 
During the crawl it finds an Error 404 for the URL:
https://www.domain.com/content/ajax/libs/jquery/3.6.0/jquery.min.js
but the correct URL is
https://www.domain.com/ajax/libs/jquery/3.6.0/jquery.min.js

The base path is set as follows:
<base href="https://www.domainname.com/content/" />

The elements to load is then loaded with ../filename

The crawler is find the file, but does not step outside of the current directory thus showing 404 errors.

Another example is for example in the source the link is
<li><a href="https://www.domainname.com/access-equipment"
The crawler tries to read it in https://www.talisman.co.za/content/access-equipment

**Comment by StJudeWasHere** [comment]
Yes, there seems to be bug with absolute urls and basepath. 
Can you confirm if this is happening only with absolute urls or do you have any case with relative url?

**Comment by ZA-OI-DE** [comment]
Will check and confirm after Monday.

**Comment by ZA-OI-DE** [comment]
If you can mail me. dirk@onlineinnovations.com then I can share the real examples that cannot be done here.

**Comment by StJudeWasHere** [comment]
Sure, you can contact me via SEonaut's email. You can find it here https://seonaut.org/support/
